import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, FileCheck2, Layers3, PenTool } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SERVICES, PERMIT_ITEMS, RESIDENTIAL, COMMERCIAL, PROCESS, REASONS, CLIENTS } from "@/lib/services";
import designImage from "@/assets/design-documentation.jpg";

export function DesignSections() {
  return <>
    <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="text-sm font-semibold uppercase text-primary">Architecture & Structural</p><h2 className="mt-4 max-w-3xl text-3xl font-bold sm:text-4xl">A coordinated foundation for your permit drawings.</h2><div className="mt-10 grid gap-10 lg:grid-cols-2">{SERVICES.filter(service => service.slug === "architectural" || service.slug === "structural").map(service => <article key={service.slug} className="border-t-2 border-primary pt-7"><service.icon className="size-10 text-primary" /><h3 className="mt-5 text-2xl font-bold">{service.title}</h3><p className="mt-4 leading-7 text-muted-foreground">{service.copy}</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{service.items.slice(0,6).map(item => <li key={item} className="flex gap-2 text-sm"><Check className="size-4 shrink-0 text-primary" />{item}</li>)}</ul>{"note" in service && <p className="mt-5 text-xs leading-6 text-muted-foreground">{service.note}</p>}<Button asChild variant="link" className="mt-5 px-0"><Link to="/services/$service" params={{service:service.slug}}>Explore this service <ArrowRight /></Link></Button></article>)}</div></div></section>
    <section id="bim" className="bg-secondary/55 py-20 sm:py-28"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2"><img src={designImage} alt="Architectural drawings and coordinated structural and MEP building model" loading="lazy" width={1408} height={1056} className="aspect-[4/3] w-full rounded-md object-cover" /><div><p className="text-sm font-semibold uppercase text-primary">BIM & Digital Drafting</p><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Clear drawings. Connected models.</h2><p className="mt-5 leading-7 text-muted-foreground">Our BIM modeling and coordination brings Architecture, Structural and MEP disciplines together for consistent documentation and early conflict review.</p><div className="mt-8 divide-y divide-border border-y border-border"><div className="flex gap-4 py-6"><PenTool className="size-7 shrink-0 text-primary" /><div><h3 className="text-xl font-bold">AutoCAD</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Precise 2D drafting for plans, elevations, sections, schedules and permit drawing details.</p></div></div><div className="flex gap-4 py-6"><Layers3 className="size-7 shrink-0 text-primary" /><div><h3 className="text-xl font-bold">Revit</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Building information models, coordinated views and schedules for architectural, structural and MEP documentation.</p></div></div></div><Button asChild className="mt-7"><Link to="/services/$service" params={{service:"bim-coordination"}}>Explore BIM Services <ArrowRight /></Link></Button></div></div></section>
    <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><FileCheck2 className="size-10 text-primary" /><h2 className="mt-5 text-3xl font-bold sm:text-4xl">Permit Drawing Packages</h2><p className="mt-5 leading-7 text-muted-foreground">We prepare permit-ready drawing packages based on project requirements and the applicable local jurisdiction.</p></div><ul className="grid gap-4 sm:grid-cols-2">{PERMIT_ITEMS.map(item => <li key={item} className="flex items-start gap-3 border-b border-border pb-3 text-sm"><Check className="size-5 shrink-0 text-primary" />{item}</li>)}</ul></div><p className="mt-8 border-l-2 border-primary pl-5 text-sm leading-7 text-muted-foreground">Final permit requirements vary by city, county, state, project type, and Authority Having Jurisdiction (AHJ).</p><div className="mt-16 grid gap-10 lg:grid-cols-2">{[{title:"Residential Design Services",copy:"We support U.S. residential projects including:",items:RESIDENTIAL},{title:"Commercial Design Services",copy:"Our drafting and design services also support:",items:COMMERCIAL}].map(group => <div key={group.title} className="border-t border-border pt-7"><h3 className="text-2xl font-bold">{group.title}</h3><p className="mt-3 text-muted-foreground">{group.copy}</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{group.items.map(item => <li key={item} className="flex gap-2 text-sm"><Check className="size-4 shrink-0 text-primary" />{item}</li>)}</ul></div>)}</div></div></section>
    <section className="bg-foreground py-20 text-primary-foreground sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="text-sm font-semibold uppercase text-primary">Our Design Process</p><h2 className="mt-4 text-3xl font-bold sm:text-4xl">From your project information to the final drawing set.</h2><div className="mt-12 grid gap-x-10 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{PROCESS.map(([title,copy],index) => <div key={title} className="border-t border-primary-foreground/20 pt-6"><span className="text-3xl font-bold text-primary">0{index+1}</span><h3 className="mt-4 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-primary-foreground/70">{copy}</p></div>)}</div></div></section>
    <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="text-sm font-semibold uppercase text-primary">Why Choose Us</p><h2 className="mt-4 max-w-3xl text-3xl font-bold sm:text-4xl">Why choose Hassan Building Design Group USA?</h2><div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{REASONS.map(([title,copy]) => <div key={title} className="border-t border-border pt-6"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{copy}</p></div>)}</div><div className="mt-14 border-t border-border pt-8"><h3 className="text-2xl font-bold">Who We Work With</h3><ul className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{CLIENTS.map(client => <li key={client} className="text-sm text-muted-foreground">{client}</li>)}</ul></div></div></section>
  </>;
}